ARG BASE_IMAGE=pibox:base
FROM ${BASE_IMAGE}

ARG PI_CODING_AGENT_VERSION=0.79.8
ARG PI_ACP_VERSION=0.0.27

RUN --mount=type=secret,id=npmrc,target=/root/.npmrc \
    npm install -g \
        @earendil-works/pi-coding-agent@${PI_CODING_AGENT_VERSION} \
        pi-acp@${PI_ACP_VERSION}
