ARG BASE_IMAGE=pibox:base
FROM ${BASE_IMAGE}

ARG PI_CODING_AGENT_VERSION=0.84.1

RUN --mount=type=secret,id=npmrc,target=/root/.npmrc \
    npm install -g \
        @earendil-works/pi-coding-agent@${PI_CODING_AGENT_VERSION}
