#!/bin/sh
#
for arg in "$@"; do
    case "$arg" in
        --headless*) echo "google-chrome: headless mode is not allowed" >&2; exit 1 ;;
    esac
done

exec /opt/google/chrome/google-chrome \
    --enable-features=UseOzonePlatform ---ozone-platform=wayland \
    --disable-gpu \
    --disable-software-rasterizer \
    --disable-dev-shm-usage \
    --no-first-run \
    --no-default-browser-check \
    --no-sandbox \
    "$@"
